### ISSUE TITLE
Delaying mock response

### ISSUE THREAD

**Issue by nurbek-ab** [muratcorlu/connect-api-mocker#16]
Is it possible to delay mock responses to simulate slow networks? I am using webpack:
```
  devServer: {
    overlay: {
      warnings: true,
      errors: true
    },
    before: (app) => {
      app.use(apiMocker('/api', 'mocks/api'));
    },
  }
```

**Comment by muratcorlu** [comment]
Normally, connect-api-mocker had a bandwidth simulation feature but because of inconsistency of it, I removed it on v1.3.0 https://github.com/muratcorlu/connect-api-mocker/releases/tag/1.3.0

If you don't need the features with 1.3.0 and later, you can try to use version 1.2.4 https://github.com/muratcorlu/connect-api-mocker/tree/1.2.4#bandwidth-simulation

**Comment by muratcorlu** [comment]
I just noticed, you can also add a delay to your responses with custom middlewares.

For example, that will respond request with a 2 sec delay:
```
module.exports = function (req, res) {
    setTimeout(function () {
         res.json({success: true);
    }, 2000);
};
```

**Comment by nurbek-ab** [comment]
Ok. Thanks.
