### ISSUE TITLE
Facing cors issue

### ISSUE THREAD

**Issue by viv3kk** [muratcorlu/connect-api-mocker#49]
Facing cors issue. I am running a CRA on 3000 and mockapi on 8080 (with express.js) and getting cors issue.

`Access to XMLHttpRequest at 'http://localhost:8080/api/orders/inspection/1021455197' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I am also using a proxy option in my package.json

**Comment by muratcorlu** [comment]
`connect-api-mocker` doesn't set CORS headers because it's intended to be part of an express(or similar) app that can be managed separately. If you want to use mocker as a standalone server I suggest to use [cli-api-mocker](https://github.com/muratcorlu/cli-api-mocker) that is also using `connect-api-mocker` internally but sending CORS headers as well.

**Comment by muratcorlu** [comment]
I'm closing this now. If you still think that is a valid issue please feel free to reopen it.
